### ISSUE TITLE
New job_option/type SHELL

### ISSUE THREAD

**Issue by victorsndvg** [MSO4SC/cloudify-hpc-plugin#3]
I've seen that there are, at least, 2 job types, `SBATCH` and `SRUN`. I think it could be useful to have a new `SHELL` type for running shell commands in a login node.

Some use cases in which this `SHELL` type could be useful:
* Remote desktop creation. We need to execute simple shell command in the visualization login node to create a new session.
* Chained steps job:
   - Step 1: compute (`SRUN` or `SBATCH` job)
   - Step 2: move files and prepare the next step (`SHELL` job)
   - Step 3: compute (`SRUN` or `SBATCH` job)

What do you think?

**Comment by victorsndvg** [comment]
## Update

If this feature is finally implemented, I think it deprecates the deployment `bootstrap` and `revert` steps.

E.g:

```yaml
# boostrap_job happens in the login node
boostrap_job:
        type: hpc.nodes.job
        properties:
            job_options: 
                type: 'SHELL'
                command: 'scripts/bootstrap.sh'
        relationships:
            - type: job_contained_in_hpc
              target: ft2_node

# parallel_job happens in compute nodes
parallel_job:
        type: hpc.nodes.job
        ...
        relationships:
            - type: job_depends_on
              target: bootstrap_job

# revert_job happens in the login node
revert_job:
        type: hpc.nodes.job
        properties:
            job_options: 
                type: 'SHELL'
                command: 'scripts/revert.sh'
        relationships:
            - type: job_contained_in_hpc
              target: ft2_node
            - type: job_depends_on
              target: parallel_job
```
to think ... :thinking:
