### ISSUE TITLE
Add job_option to activate/desactive job

### ISSUE THREAD

**Issue by gdolle** [MSO4SC/cloudify-hpc-plugin#8]
It would be nice to have a new option to desactivate jobs via a portal button, or user input
for blueprint having several (optional) jobs
```yaml
job1:
    job_options:
        enable: false
job2:
    job_options
        enable: true  # default
```
