### ISSUE TITLE
Bug with YAML anchor

### ISSUE THREAD

**Issue by gdolle** [MSO4SC/cloudify-hpc-plugin#9]
We should be able to use YAML anchor,
http://docs.getcloudify.org/dev/blueprints/spec-dsl-definitions/

But it seems the sbatch there's a bug with the parser. The generated slurm batch script generated
goes wrong with get_input entries.

For example we might want to do something like this:

```yaml
# blueprint
dsl_definitions:
    # Create an alias
    - &job_properties_default
          modules:
              - gcc/6.4.0
              - openmpi/1.10.7_gcc640
          partition: 'public'
          home: '${HOME}:/home/${USER}'
          volumes:
              - '/scratch'
              - '${HOME}/test:/test'
          image: '${HOME}/singularity.simg'
          command: 'echo failed'
          nodes: 1
          tasks: 1
          tasks_per_node: 1
          max_time: '00:10:00'

#   ...

node_types:
    myjob:
        type: hpc.nodes.singularity_job
        job_options:
            default:
                <<: *job_properties_default # Call the alias
                command: echo "toto"  # Override command key only !
```
